"""
Save extraction results (JSON fields + Excel binary) to NeonDB.

Schema lives in schema.sql. Anything not given an explicit column lands in
the `raw_json` JSONB column on the same row, so nothing is ever lost.
"""
from psycopg.types.json import Jsonb

from database.connection import get_connection
from database.setup import ensure_schema


def _safe_num(val):
    """Coerce to numeric or None. NeonDB NUMERIC handles int/float natively."""
    if val is None:
        return None
    if isinstance(val, (int, float)):
        return val
    try:
        return float(val)
    except (TypeError, ValueError):
        return None


def _safe_int(val):
    n = _safe_num(val)
    return int(n) if n is not None else None


def _safe_bool(val):
    if val is None:
        return None
    if isinstance(val, bool):
        return val
    if isinstance(val, str):
        v = val.strip().lower()
        if v in ("true", "yes", "y", "1"):
            return True
        if v in ("false", "no", "n", "0"):
            return False
    return None


def save_extraction(data: dict, excel_bytes: bytes, excel_filename: str) -> int:
    """
    Insert one extraction (parent row + per-plan child rows + per-tranche
    grandchild rows) into NeonDB.

    Args:
        data: Parsed JSON dict produced by the extractor.
        excel_bytes: Raw .xlsx file bytes generated by build_workbook.
        excel_filename: Filename to record (e.g. "eli.xlsx").

    Returns:
        New extractions.id.
    """
    ensure_schema()

    plans = data.get("plans") or []
    meta = data.get("_meta") or {}
    cost = (meta.get("cost") or {}).get("total_cost_usd")
    val_summary = data.get("_validation_summary") or {}
    warnings_cnt = len(val_summary.get("warnings") or [])

    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO extractions (
                    company_name, report_period, currency, reporting_standard,
                    source_pdf, total_plans, extraction_cost_usd,
                    total_pdf_pages, pages_processed,
                    extraction_model, classifier_model, extraction_mode,
                    validation_warnings_cnt,
                    raw_json, excel_file, excel_filename
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING id
                """,
                (
                    data.get("company_name"),
                    data.get("report_period"),
                    data.get("currency"),
                    data.get("reporting_standard"),
                    meta.get("source_pdf"),
                    len(plans),
                    _safe_num(cost),
                    _safe_int(meta.get("total_pdf_pages")),
                    meta.get("pages_processed") or None,
                    meta.get("model"),
                    (meta.get("detection") or {}).get("stage2_classifier"),
                    meta.get("mode"),
                    warnings_cnt,
                    Jsonb(data),
                    excel_bytes,
                    excel_filename,
                ),
            )
            extraction_id = cur.fetchone()[0]

            for plan in plans:
                plan_id = _insert_plan(cur, extraction_id, plan)
                for idx, tranche in enumerate(plan.get("tranches") or []):
                    _insert_tranche(cur, plan_id, idx, tranche)

    return extraction_id


# ── Helpers ──────────────────────────────────────────────────────────

def _insert_plan(cur, extraction_id: int, plan: dict) -> int:
    """Insert one plan row, return the new plans.id."""
    valuation = plan.get("valuation_inputs") or {}
    prior = plan.get("prior_year") or {}

    cur.execute(
        """
        INSERT INTO plans (
            extraction_id,
            plan_name, plan_type, plan_description,
            opening_balance, granted, exercised, forfeited_or_lapsed,
            vested, closing_balance, exercisable_at_period_end,
            weighted_avg_exercise_price, weighted_avg_exercise_price_unit,
            weighted_avg_grant_date_fair_value, fair_value_unit,
            exercise_price_range_low, exercise_price_range_high, exercise_price_range_unit,
            weighted_avg_remaining_contractual_life_years,
            weighted_avg_share_price_at_exercise,
            weighted_avg_share_price_at_exercise_unit,
            units_label, vesting_period_years, performance_period_years, holding_period_years,
            vesting_description, performance_conditions,
            is_nil_cost, is_cash_settled,
            total_contingent_awards, contingent_cash_settled, contingent_equity_settled,
            valuation_model,
            valuation_volatility_pct, valuation_risk_free_rate_pct,
            valuation_dividend_yield_pct, valuation_expected_life_years,
            valuation_stock_price, valuation_stock_price_unit,
            valuation_strike_price,
            valuation_fair_value_per_option, valuation_fair_value_unit,
            prior_opening_balance, prior_granted, prior_exercised, prior_vested,
            prior_forfeited_or_lapsed, prior_closing_balance,
            prior_weighted_avg_exercise_price, prior_weighted_avg_grant_date_fair_value,
            raw_json
        )
        VALUES (
            %s,
            %s, %s, %s,
            %s, %s, %s, %s,
            %s, %s, %s,
            %s, %s,
            %s, %s,
            %s, %s, %s,
            %s,
            %s,
            %s,
            %s, %s, %s, %s,
            %s, %s,
            %s, %s,
            %s, %s, %s,
            %s,
            %s, %s,
            %s, %s,
            %s, %s,
            %s,
            %s, %s,
            %s, %s, %s, %s,
            %s, %s,
            %s, %s,
            %s
        )
        RETURNING id
        """,
        (
            extraction_id,
            plan.get("plan_name"),
            plan.get("plan_type"),
            plan.get("plan_description"),

            _safe_num(plan.get("opening_balance")),
            _safe_num(plan.get("granted")),
            _safe_num(plan.get("exercised")),
            _safe_num(plan.get("forfeited_or_lapsed")),
            _safe_num(plan.get("vested")),
            _safe_num(plan.get("closing_balance")),
            _safe_num(plan.get("exercisable_at_period_end")),

            _safe_num(plan.get("weighted_avg_exercise_price")),
            plan.get("weighted_avg_exercise_price_unit"),
            _safe_num(plan.get("weighted_avg_grant_date_fair_value")),
            plan.get("fair_value_unit"),

            _safe_num(plan.get("exercise_price_range_low")),
            _safe_num(plan.get("exercise_price_range_high")),
            plan.get("exercise_price_range_unit"),

            _safe_num(plan.get("weighted_avg_remaining_contractual_life_years")),
            _safe_num(plan.get("weighted_avg_share_price_at_exercise")),
            plan.get("weighted_avg_share_price_at_exercise_unit"),

            plan.get("units_label"),
            _safe_num(plan.get("vesting_period_years")),
            _safe_num(plan.get("performance_period_years")),
            _safe_num(plan.get("holding_period_years")),

            plan.get("vesting_description"),
            plan.get("performance_conditions"),

            _safe_bool(plan.get("is_nil_cost")),
            _safe_bool(plan.get("is_cash_settled")),

            _safe_num(plan.get("total_contingent_awards")),
            _safe_num(plan.get("contingent_cash_settled")),
            _safe_num(plan.get("contingent_equity_settled")),

            plan.get("valuation_model"),
            _safe_num(valuation.get("volatility_pct")),
            _safe_num(valuation.get("risk_free_rate_pct")),
            _safe_num(valuation.get("dividend_yield_pct")),
            _safe_num(valuation.get("expected_life_years")),
            _safe_num(valuation.get("stock_price")),
            valuation.get("stock_price_unit"),
            _safe_num(valuation.get("strike_price")),
            _safe_num(valuation.get("fair_value_per_option")),
            valuation.get("fair_value_unit"),

            _safe_num(prior.get("opening_balance")),
            _safe_num(prior.get("granted")),
            _safe_num(prior.get("exercised")),
            _safe_num(prior.get("vested")),
            _safe_num(prior.get("forfeited_or_lapsed")),
            _safe_num(prior.get("closing_balance")),
            _safe_num(prior.get("weighted_avg_exercise_price")),
            _safe_num(prior.get("weighted_avg_grant_date_fair_value")),

            Jsonb(plan),
        ),
    )
    return cur.fetchone()[0]


def _insert_tranche(cur, plan_id: int, idx: int, tranche: dict) -> None:
    cur.execute(
        """
        INSERT INTO plan_tranches (
            plan_id, tranche_index,
            grant_date, shares_granted, shares_at_period_end,
            grant_price, grant_price_unit,
            exercise_price, exercise_price_unit,
            vesting_period_years,
            fair_value_per_option, fair_value_unit,
            raw_json
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """,
        (
            plan_id,
            idx,
            tranche.get("grant_date"),
            _safe_num(tranche.get("shares_granted")),
            _safe_num(tranche.get("shares_at_period_end")),
            _safe_num(tranche.get("grant_price")),
            tranche.get("grant_price_unit"),
            _safe_num(tranche.get("exercise_price")),
            tranche.get("exercise_price_unit"),
            _safe_num(tranche.get("vesting_period_years")),
            _safe_num(tranche.get("fair_value_per_option")),
            tranche.get("fair_value_unit"),
            Jsonb(tranche),
        ),
    )
